export type RootStackParamList = {
  Login: undefined;
  Signup: undefined;
  Tabs: undefined;
  Profile: undefined;
  EditNameScreen: undefined;
  AgePickerScreen: undefined;
  GenderScreen: undefined;
  brandCards: undefined;
  searchCarCards: undefined;
  passwordSecurity: undefined;
  NotificationPreference: undefined;
  faqs: undefined;
  privacyPolicy: undefined;
  report: undefined;
  logout: undefined;
  changePassword: undefined;
  extendLease: undefined;
  carDetails: undefined;
};
